version: "3"
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     JWT_SECRET: CHANGE_ME
  #     DATABASE_URL: "mysql://user:password@database:3306/data"
  #     REDIS_URL: "redis://default:redispassword@redis:6379"
  #   depends_on:
  #     - database
  #     - redis
  database:
    image: mariadb:10.9.4
    restart: always
    environment:
      MARIADB_DATABASE: "data"
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "password"
      MARIADB_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mariadb
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "redispassword"]
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge
